openapi: 3.1.0
info:
  title: DW API
  description: API para consultar pedidos do Data Warehouse.
  version: 1.0.0
servers:
  - url: https://keuvinbaumgartel.github.io/DW_API_Project
paths:
  /pedidos:
    get:
      operationId: getPedidos
      summary: Retorna os primeiros 50 pedidos.
      responses:
        '200':
          description: Lista de pedidos.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pedido'
        '500':
          description: Erro ao buscar pedidos.
components:
  schemas:
    Pedido:
      type: object
      properties:
        pedido:
          type: string
        data_pedido:
          type: string
        pedido_externo:
          type: string
        pedido_cliente:
          type: string
        tipo_pedido:
          type: string
        filial:
          type: string
        canal:
          type: string
        cod_cliente:
          type: string
        transportadora:
          type: string
        moeda:
          type: string
        tot_valor_original:
          type: number
        tot_valor_entregue:
          type: number
        tot_valor_cancelado:
          type: number
        desconto:
          type: number
